/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.apautomation.deep;import cn.zhuatech.apautomation.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                           */
@RestController @RequestMapping("/api/admin/ap") public class DeepAdminController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                               */
public DeepAdminController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                         */
@PostMapping("/invoices/{id}/approve")ApiResponse<?> approve(@PathVariable Long id){return ApiResponse.ok(s.approve(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/invoices/{id}/payment-plans")ApiResponse<?> schedule(@PathVariable Long id,@Valid @RequestBody DeepDomainService.PaymentRequest r){return ApiResponse.ok(s.schedule(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@PostMapping("/payment-plans/{id}/pay")ApiResponse<?> pay(@PathVariable Long id,@Valid @RequestBody DeepDomainService.PayRequest r){return ApiResponse.ok(s.pay(id,r));}}
