/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.apautomation.deep;import cn.zhuatech.apautomation.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                           */
@RestController @RequestMapping("/api/ap") public class DeepDomainController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                          */
public DeepDomainController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                     */
@GetMapping("/dashboard")ApiResponse<?> dashboard(@RequestParam String organizationCode){return ApiResponse.ok(s.dashboard(organizationCode));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/purchase-order-lines")ApiResponse<?> po(@Valid @RequestBody DeepDomainService.PoLineRequest r){return ApiResponse.ok(s.createPo(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
@PostMapping("/purchase-order-lines/{id}/receipts")ApiResponse<?> receipt(@PathVariable Long id,@Valid @RequestBody DeepDomainService.ReceiptRequest r){return ApiResponse.ok(s.receive(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
@PostMapping("/invoices")ApiResponse<?> invoice(@Valid @RequestBody DeepDomainService.InvoiceRequest r){return ApiResponse.ok(s.createInvoice(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@PostMapping("/invoices/{id}/match")ApiResponse<?> match(@PathVariable Long id,@Valid @RequestBody DeepDomainService.MatchRequest r){return ApiResponse.ok(s.match(id,r));}}
