/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.apautomation;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.Pattern;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest @AutoConfigureMockMvc class DeepApAutomationTests{@Autowired MockMvc mvc;
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void lineLevelThreeWayMatchApprovalAndPaymentWork()throws Exception{long po=po("UT-PO-01",100,100);receipt(po,"UT-GR-01",100);long invoice=invoice("UT-INV-01","UT-PO-01",100,100);mvc.perform(post("/api/ap/invoices/{id}/match",invoice).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"tolerancePercent\":0.5}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("MATCHED")).andExpect(jsonPath("$.data.exceptionCount").value(0));mvc.perform(post("/api/admin/ap/invoices/{id}/approve",invoice).with(httpBasic("admin","admin123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("APPROVED"));long plan=idOf(mvc.perform(post("/api/admin/ap/invoices/{id}/payment-plans",invoice).with(httpBasic("admin","admin123")).contentType(MediaType.APPLICATION_JSON).content("{\"paymentDate\":\"2026-09-30\",\"amount\":10000,\"bankAccountMask\":\"****8888\"}")).andExpect(status().isOk()).andReturn());mvc.perform(post("/api/admin/ap/payment-plans/{id}/pay",plan).with(httpBasic("admin","admin123")).contentType(MediaType.APPLICATION_JSON).content("{\"paymentReference\":\"PAY-UT-001\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("PAID"));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void amountVarianceCreatesExceptionAndBlocksApproval()throws Exception{long po=po("UT-PO-02",100,100);receipt(po,"UT-GR-02",50);long invoice=invoice("UT-INV-02","UT-PO-02",100,100);mvc.perform(post("/api/ap/invoices/{id}/match",invoice).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"tolerancePercent\":1}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("EXCEPTION")).andExpect(jsonPath("$.data.exceptionCount").value(1));mvc.perform(post("/api/admin/ap/invoices/{id}/approve",invoice).with(httpBasic("admin","admin123"))).andExpect(status().isConflict());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void overReceiptAndUnbalancedInvoiceAreRejected()throws Exception{long po=po("UT-PO-03",10,20);mvc.perform(post("/api/ap/purchase-order-lines/{id}/receipts",po).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"receiptNo\":\"UT-GR-BAD\",\"quantity\":11,\"receiptDate\":\"2026-08-27\",\"receiver\":\"仓管员\"}")).andExpect(status().isConflict());mvc.perform(post("/api/ap/invoices").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"organizationCode\":\"UT-AP\",\"vendorCode\":\"V001\",\"invoiceNo\":\"UT-INV-BAD\",\"currency\":\"CNY\",\"totalAmount\":999,\"taxAmount\":0,\"invoiceDate\":\"2026-08-27\",\"dueDate\":\"2026-09-30\",\"lines\":[{\"lineNo\":1,\"poNo\":\"UT-PO-03\",\"poLineNo\":1,\"itemCode\":\"ITEM-01\",\"quantity\":10,\"unitPrice\":20}]}")).andExpect(status().isBadRequest());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private long po(String no,int qty,int price)throws Exception{return idOf(mvc.perform(post("/api/ap/purchase-order-lines").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"organizationCode\":\"UT-AP\",\"poNo\":\""+no+"\",\"lineNo\":1,\"vendorCode\":\"V001\",\"itemCode\":\"ITEM-01\",\"orderedQty\":"+qty+",\"unitPrice\":"+price+"}")).andExpect(status().isOk()).andReturn());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                     */
private void receipt(long id,String no,int qty)throws Exception{mvc.perform(post("/api/ap/purchase-order-lines/{id}/receipts",id).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"receiptNo\":\""+no+"\",\"quantity\":"+qty+",\"receiptDate\":\"2026-08-27\",\"receiver\":\"仓管员\"}")).andExpect(status().isOk());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
private long invoice(String no,String po,int qty,int price)throws Exception{return idOf(mvc.perform(post("/api/ap/invoices").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"organizationCode\":\"UT-AP\",\"vendorCode\":\"V001\",\"invoiceNo\":\""+no+"\",\"currency\":\"CNY\",\"totalAmount\":"+(qty*price)+",\"taxAmount\":0,\"invoiceDate\":\"2026-08-27\",\"dueDate\":\"2026-09-30\",\"lines\":[{\"lineNo\":1,\"poNo\":\""+po+"\",\"poLineNo\":1,\"itemCode\":\"ITEM-01\",\"quantity\":"+qty+",\"unitPrice\":"+price+"}]}")).andExpect(status().isOk()).andReturn());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
private long idOf(MvcResult r)throws Exception{var m=Pattern.compile("\"id\":(\\d+)").matcher(r.getResponse().getContentAsString());Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}}
